services:
  verifier:
    build: .
    container_name: email-verifier
    restart: unless-stopped
    ports:
      - "5002:5002"
    volumes:
      - ./app.py:/app/app.py
      - ./templates:/app/templates
      - ./verifier.db:/app/verifier.db
      - ./data:/app/data
    environment:
      - TZ=Europe/Madrid
